# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: my mind and the machine
email: robert.meyer.oe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is yet another blog about science, math, code, and other nerdy 
  stuff that comes across my computer.
baseurl: "/mymindandthemachine" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  SmokinCaterpillar



# Post sharing icons
sharing:
    twitter: true
    linkedin: true
    facebook: true
    google_plus: true
    reddit: true

# Disqus comments configuration (leave blank to disable comments)
disqus_shortname: 'mymindandthemachine'

# Build settings
markdown: kramdown

gems:
- jekyll-seo-tag
